FROM ubuntu:16.04

RUN sed -e s%http://archive.ubuntu.com/ubuntu/%mirror://mirrors.ubuntu.com/mirrors.txt% -i /etc/apt/sources.list \
        && apt-get update \
        && apt-get dist-upgrade -y \
        && apt-get install -y nano python3

ENV MAPNIK_VERSION=3.0.9+ds-1 \
    PYTHON_MAPNIK_VERSION=1:0.0~20151125-92e79d2-1build1

RUN apt-get update \
 && apt-get install -y \
            libmapnik3.0=${MAPNIK_VERSION} \
            libmapnik-dev=${MAPNIK_VERSION} \
            mapnik-utils=${MAPNIK_VERSION} \
            python-mapnik=${PYTHON_MAPNIK_VERSION} \
            python3-mapnik=${PYTHON_MAPNIK_VERSION} \
     && python -c 'import mapnik'

RUN apt-get install -y python-setuptools python-pip